version: '3.8'

services:
  api:
    build: ./api-server
    ports:
      - "8080:8080"
    environment:
      -.env;

  rt:
    build: ./rt-server
    ports:
      - "8081:8081"

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - api
      - rt